OpenHand/urls.py
from projects import views
"""OpenHand URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('organizations/', views.OrganizationListView.as_view(), name='organizations'),
    path('organization/<int:pk>', views.OrganizationDetailView.as_view(), name='organization'),
    path('campaigns/', views.CampaignListView.as_view(), name='campaigns'),
    path('campaign/<int:pk>', views.CampaignDetailView.as_view(), name='campaign'),
]

projects/models.py
from django.db import models
from django.urls import reverse


class Campaign(models.Model):
    name = models.CharField(max_length = 40)
    description = models.TextField()
    organization = models.ForeignKey('Organization', on_delete = models.CASCADE)
    FUNDING_STATUS = (
        ('p', 'Pending'),
        ('a', 'Active'),
        ('s', 'Successful'),
        ('c', 'Closed'),
        ('i', 'Inactive')
    )
    status = models.CharField(max_length=1, choices=FUNDING_STATUS, blank=True, default='m', help_text='Campaign Funding Status')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('model-detail-view', args=[str(self.id)])


class Organization(models.Model):
    name = models.CharField(max_length = 40)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('organization', args=[str(self.id)])


class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular user instance.
        """
        return reverse('user-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.last_name, self.first_name)


class Donation(models.Model):
        """
        Model representing a specific copy of a book (i.e. that can be borrowed from the library).
        """
        campaign = models.ForeignKey('Campaign', on_delete=models.SET_NULL, null=True)
        donor = models.ForeignKey('User', on_delete = "Protect")
        date = models.DateField(null=True, blank=True)
        amount = models.CharField('Amount', max_length=10)
        currency = models.CharField('Currency', max_length=3)

        def __str__(self):
            """
            String for representing the Model object
            """
            return '{0} ({1})'.format(self.id, self.book.title)

projects/views.py
from django.shortcuts import render
from .models import Campaign, Organization, Donation, User
from django.views import generic


class OrganizationListView(generic.ListView):
    model = Organization
    #context_object_name = 'all_org_list'  # your own name for the list as a template variable
    #queryset = Organization.objects.filter(name__icontains='foundation')[:5]
    #template_name = 'organizations/my_arbitrary_template_name_list.html'  # Specify your own template name/location

    #def get_queryset(self):
    #   return Organization.objects.filter(name__icontains='child')[:5]  # Get 5 organizations containing child


class OrganizationDetailView(generic.DetailView):
    model = Organization

class CampaignListView(generic.ListView):
    model = Campaign

class CampaignDetailView(generic.DetailView):
    model = Campaign


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_campaigns = Campaign.objects.all().count()
    num_organizations = Organization.objects.all().count()
    num_successful_campaigns = Campaign.objects.filter(status__exact='s').count()
    num_users = User.objects.count()

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_organizations': num_organizations, 'num_campaigns': num_campaigns,
                 'num_successful_campaigns': num_successful_campaigns, 'num_users': num_users},
    )

projects/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Open Hand Society</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'organizations' %}">All organizations</a></li>
          <li><a href="">All campaigns</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

projects/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Crowdfunding Home</h1>

  <p>Welcome to <em>Open Hand Platform</em>.

<h2>Stats</h2>

  <p>Platform has the following record counts:</p>
  <ul>
    <li><strong>Organizations:</strong> {{ num_organizations }}</li>
    <li><strong>Campaigns:</strong> {{ num_campaigns }}</li>
    <li><strong>Successful Campaigns:</strong> {{ num_successful_campaigns }}</li>
    <li><strong>Authors:</strong> {{ num_users }}</li>
  </ul>

{% endblock %}

projects/templates/projects/organization_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ organization.name }}</h1>

  <p><strong>description:</strong> {{ organization.description }}</p>


  <div style="margin-left:20px;margin-top:20px">
    <h4>Campaigns</h4>

    {% for campaign in organization.campaign_set.all %}
    <hr>
    <p class="{% if campaign.status == 'a' %}text-success{% elif campaign.status == 'm' %}text-danger
    {% else %}text-warning{% endif %}">{{ campaign.get_status_display }}</p>
    <p class="text-muted"><strong>Id:</strong> {{campaign.id}}</p>
    {% endfor %}
  </div>'''
{% endblock %}

projects/templates/projects/organization_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Organization List</h1>

    {% if organization_list %}
    <ul>

      {% for organization in organization_list %}
      <li>
        <a href="{{ organization.get_absolute_url }}"> {{ organization.name }}</a> ({{organization.description}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no organizations in the system.</p>
    {% endif %}       
{% endblock %}